version: '3.7'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "secretpassword"
      MONGO_INITDB_DATABASE: "hha"
    volumes:
      - "./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secretpassword
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: always
  hha-spring:
    build: './back-end/hha'
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      MONGODB_HOST: "mongodb"
  hha-react:
    build: './front-end/hha-front-end'
    ports:
      - "443:3000"
networks:
  default:
    ipam:
      config:
        - subnet: 172.33.0.0/16